version: '3'
services:
  nextjs:
    container_name: nextjs
    build: ./client
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      NEXT_PUBLIC_MAIN_PORT: ${MAIN_PORT}
      NEXT_PUBLIC_API_PORT: ${API_PORT}
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  postgres:
    container_name: pg_db
    restart: always
    image: postgres:15.2-alpine
    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: production
    ports:
      - "5432:5432"
  expressjs:
    container_name: express-api
    restart: always
    depends_on:
      - postgres
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ../server/static:/server/static
  admin-react:
    container_name: admin-react
    restart: always
    build: ./admin
    ports:
      - "3030:3000"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ildar@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  php:
    image: php:8.1-fpm
    volumes:
      - './phpSrc:/var/www/html'
volumes:
  postgres-data:
