version: '3'
services:
  nextjs:
    container_name: nextjs
    build: ./client
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  postgres:
    container_name: pg_db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  expressjs:
    container_name: express-api
    restart: always
    depends_on:
      - postgres
    build: ./server
    ports:
      - "5000:5000"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ildar@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
