version: '3'
services:
  nextjs:
    build: ./client
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  expressjs:
    build: ./server
  postgres:
    image: postgres:14.7
    environment:
      POSTGRES_DB: "production"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
