version: '3'
services:
  nextjs:
    build: ./client
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "production"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
  expressjs:
    depends_on:
      - postgres
    build: ./server
