import Head from 'next/head'
import Image from 'next/image'
import React from "react";


export default function Home() {
    return (
        <>
            <Head>
                <title>E-commerce</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div>index</div>
                <Image src={`http://smarthome16.ru:5000/productImages/25c472a7-81bd-41d4-a806-9666e4713ce6.jpeg`} fill
                       alt="" className="product__image-img"/>

            </main>
        </>
    )
}
